---
- hosts: ip0*
  tasks:
    - name: "Apache 설치"
      yum:
        name: httpd
        state: present
      become: true
    - name: "Apache 시작"
      service:
        name: httpd
        state: started
        enabled: true
      become: true
#    - name: "기본 httpd.conf 입력"
#      template:
#        src: website.conf
#        dest: /etc/httpd/conf/httpd.conf
#      become: true
#      notify: "httpd 재시작"
#    - name: "재시작 먼저"
#      meta: flush_handlers
    - name: "httpd Listen IP 기록"
      shell: "netstat -an|grep 80|grep LISTEN"
      register: listenStatus
    - name: "httpd Listen IP 확인"
      debug:
        msg: '{{ listenStatus.stdout }}'
#  handlers:
#    - name: "httpd 재시작"
#      service:
#        name: httpd
#        state: restarted
#      become: true